### ISSUE TITLE
Feature: Request

### ISSUE THREAD

**Issue by StyxOfDynamite** [dbough/vagrant-ghost#3]
I've added `config.vm.synced_folder "ghost/", "/var/www/ghost"`

This allows you to sync the ghost folder to your local machine, Not sure if it's worth submitting a pull request but it does make theme editing a lot easier when you don't have to SCP files / SSH into the Vagrant box to develop a theme.

**Comment by dbough** [comment]
Hi @StyxOfDynamite -

I'd be happy to add it if you think it's useful.  Would you mind submitting a pull request?

Thanks

**Comment by StyxOfDynamite** [comment]
I looked at submitting it, but it made more sense to me to build a whole box with the latest version. I would have used the Ghost distributed one but it doesn't work on my machine (Yay! Vagrant fixing problems I didn't know existed by distracting me with a new set of problems)

Decided basically at this moment in time its just easier to clone VMs.
